# GIRAFF Channel Specifications returned as Python Dictionary
# Converted from GIRAFF Channel specs v1.pdf

#Written by Aaron Breneman, May 23, 2025.

#Used files
#GIRAFF380 channel spec with conversion equations.pdf
#GIRAFF381 _CORRECTED_ channel spec with conversion equations.pdf

#AI prompt: 
    #Please convert the first three rows of the attached file into a Python dictionary. Include columns with no values. The column names are as follows: signal, analog_filter, analog_output, testpoint+, testpoint-, tm, fs, max_sig_pm_mV, boom_length, max_sig_pm_mVm, gain_desired, gaindB_desired, gain_measured, gaindB_measured, measured_mVm, hpf, lpf, bits, coeffa, coeffb, polarity
#AI followup: 
    #Thanks. This is mostly correct with the exceptions of the "hpf" , "lpf", and "bits" columns. For reference, the values of these in the first row are hpf=None, lpf=14.000, bits=18. Please redo

def gir_cal_channel_data():

    # GIRAFF380 channel specification - All rows as Python dictionary
    # from file GIRAFF380 channel spec with conversion equations.pdf
    giraff_data380 = [
        {
            "signal": "V12D",
            "analog_filter": "F4-3",
            "analog_output": None,
            "testpoint_plus": "U72-4",
            "testpoint_minus": "U72-5",
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 1251,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 385.0,
            "gain_desired": 2.00,
            "gaindB_desired": 6.0,
            "gain_measured": 1.963,
            "gaindB_measured": 5.860,
            "measured_mVm": 392,
            "hpf": None,
            "lpf": 14000.,
            "bits": 18,
            "coeffa": 1.2733E+00,
            "coeffb": 4.6059E-04,
            "polarity": "Pos"
        },
        {
            "signal": "V34D",
            "analog_filter": "F4-4",
            "analog_output": None,
            "testpoint_plus": "U67-4",
            "testpoint_minus": "U67-5",
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 1251,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 385.0,
            "gain_desired": 2.00,
            "gaindB_desired": 6.0,
            "gain_measured": 1.964,
            "gaindB_measured": 5.861,
            "measured_mVm": 392,
            "hpf": None,
            "lpf": 14000.,
            "bits": 18,
            "coeffa": 1.2732E+00,
            "coeffb": 1.3000E-03,
            "polarity": "Pos"
        },
        {
            "signal": "Only ADC",
            "analog_filter": "F4-1",
            "analog_output": None,
            "testpoint_plus": "U81-4",
            "testpoint_minus": "U81-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 625,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 272.0,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 28000.,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "Only ADC",
            "analog_filter": "F4-5",
            "analog_output": None,
            "testpoint_plus": "U62-4",
            "testpoint_minus": "U62-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 625,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 272.0,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 28000.,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "Only ADC",
            "analog_filter": "F4-6",
            "analog_output": None,
            "testpoint_plus": "U58-4",
            "testpoint_minus": "U58-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 625,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 272.0,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 28000.,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "VLF41DADC/VLF12A FiltF4-2",
            "analog_filter": None,
            "analog_output": None,
            "testpoint_plus": "U77-4",
            "testpoint_minus": "U77-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 625,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 272.0,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 28000.,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "VLF12D",
            "analog_filter": "F8-3",
            "analog_output": None,
            "testpoint_plus": "U33-4",
            "testpoint_minus": "U33-5",
            "tm": 1000000,
            "fs": 1000000,
            "max_sig_pm_mV": 125,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 38.5,
            "gain_desired": 20.00,
            "gaindB_desired": 26.0,
            "gain_measured": 20.032,
            "gaindB_measured": 26.035,
            "measured_mVm": 38,
            "hpf": 50.,
            "lpf": 437500.,
            "bits": 18,
            "coeffa": 1.2480E-01,
            "coeffb": -5.5000E-05,
            "polarity": "Pos"
        },
        {
            "signal": "VLF34D",
            "analog_filter": "F8-4",
            "analog_output": None,
            "testpoint_plus": "U28-4",
            "testpoint_minus": "U28-5",
            "tm": 1000000,
            "fs": 1000000,
            "max_sig_pm_mV": 125,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 38.5,
            "gain_desired": 20.00,
            "gaindB_desired": 26.0,
            "gain_measured": 20.064,
            "gaindB_measured": 26.048,
            "measured_mVm": 38,
            "hpf": 50.,
            "lpf": 437500.,
            "bits": 18,
            "coeffa": 1.2460E-01,
            "coeffb": 6.2200E-06,
            "polarity": "Pos"
        },
        {
            "signal": "VLF13D",
            "analog_filter": "F8-1/F4-1ADC",
            "analog_output": None,
            "testpoint_plus": "U81-4",
            "testpoint_minus": "U81-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 62,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 27.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": 40.584,
            "gaindB_measured": 32.167,
            "measured_mVm": 27,
            "hpf": 50.,
            "lpf": 28000.,
            "bits": 18,
            "coeffa": 6.1600E-02,
            "coeffb": 1.5823E-05,
            "polarity": "Pos"
        },
        {
            "signal": "VLF32D",
            "analog_filter": "F8-5/F4-5ADC",
            "analog_output": None,
            "testpoint_plus": "U62-4",
            "testpoint_minus": "U62-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 62,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 27.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": 39.620,
            "gaindB_measured": 31.958,
            "measured_mVm": 27,
            "hpf": 50.,
            "lpf": 28000.,
            "bits": 18,
            "coeffa": 6.3100E-02,
            "coeffb": 1.2659E-06,
            "polarity": "Pos"
        },
        {
            "signal": "VLF24D",
            "analog_filter": "F8-6/F4-6ADC",
            "analog_output": None,
            "testpoint_plus": "U58-4",
            "testpoint_minus": "U58-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 62,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 27.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": 40.453,
            "gaindB_measured": 32.139,
            "measured_mVm": 27,
            "hpf": 50.,
            "lpf": 28000.,
            "bits": 18,
            "coeffa": 6.1800E-02,
            "coeffb": 6.8071E-06,
            "polarity": "Neg"
        },
        {
            "signal": "VLF41D",
            "analog_filter": "F8-2/F4-2ADC",
            "analog_output": None,
            "testpoint_plus": "U77-4",
            "testpoint_minus": "U77-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 62,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 27.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": 38.700,
            "gaindB_measured": 31.754,
            "measured_mVm": 28,
            "hpf": 50.,
            "lpf": 28000.,
            "bits": 18,
            "coeffa": 6.4600E-02,
            "coeffb": 7.3297E-06,
            "polarity": "Neg"
        },
        {
            "signal": "V1SD",
            "analog_filter": "MUX5",
            "analog_output": None,
            "testpoint_plus": "U55-7",
            "testpoint_minus": None,
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 5000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.5,
            "gaindB_desired": -6.0,
            "gain_measured": 0.509,
            "gaindB_measured": -5.871,
            "measured_mVm": 4915,
            "hpf": None,
            "lpf": 14000.,
            "bits": 18,
            "coeffa": -4.9145E+00,
            "coeffb": -2.3000E-03,
            "polarity": "Neg"
        },
        {
            "signal": "V2SD",
            "analog_filter": "MUX6",
            "analog_output": None,
            "testpoint_plus": "U54-7",
            "testpoint_minus": None,
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 5000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.5,
            "gaindB_desired": -6.0,
            "gain_measured": 0.509,
            "gaindB_measured": -5.870,
            "measured_mVm": 4914,
            "hpf": None,
            "lpf": 14000.,
            "bits": 18,
            "coeffa": -4.9139E+00,
            "coeffb": -2.5000E-03,
            "polarity": "Neg"
        },
        {
            "signal": "V3SD",
            "analog_filter": "MUX7",
            "analog_output": None,
            "testpoint_plus": "U55-1",
            "testpoint_minus": None,
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 5000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.5,
            "gaindB_desired": -6.0,
            "gain_measured": 0.509,
            "gaindB_measured": -5.872,
            "measured_mVm": 4915,
            "hpf": None,
            "lpf": 14000.,
            "bits": 18,
            "coeffa": -4.9153E+00,
            "coeffb": -2.8000E-03,
            "polarity": "Neg"
        },
        {
            "signal": "V4SD",
            "analog_filter": "MUX4",
            "analog_output": None,
            "testpoint_plus": "U54-1",
            "testpoint_minus": None,
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 5000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.5,
            "gaindB_desired": -6.0,
            "gain_measured": 0.508,
            "gaindB_measured": -5.879,
            "measured_mVm": 4919,
            "hpf": None,
            "lpf": 14000.,
            "bits": 18,
            "coeffa": -4.9193E+00,
            "coeffb": -2.7000E-03,
            "polarity": "Neg"
        },
        {
            "signal": "V12A",
            "analog_filter": "F4-3",
            "analog_output": "J6-5",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 2000,
            "fs": None,
            "max_sig_pm_mV": 625,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 192.3,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875.,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V34A",
            "analog_filter": "F4-4",
            "analog_output": "J6-13",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 2000,
            "fs": None,
            "max_sig_pm_mV": 625,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 192.3,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875.,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "VLF12A",
            "analog_filter": "F8-3",
            "analog_output": "J6-11",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 32000,
            "fs": None,
            "max_sig_pm_mV": 62,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 19.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": 50.,
            "lpf": 14000.,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V1SA",
            "analog_filter": "U51B",
            "analog_output": "J6-3",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 1000,
            "fs": None,
            "max_sig_pm_mV": 10000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.25,
            "gaindB_desired": -12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 438.,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V2SA",
            "analog_filter": "U51D",
            "analog_output": "J6-2",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 1000,
            "fs": None,
            "max_sig_pm_mV": 10000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.25,
            "gaindB_desired": -12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 438.,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V3SA",
            "analog_filter": "U51C",
            "analog_output": "J6-4",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 1000,
            "fs": None,
            "max_sig_pm_mV": 10000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.25,
            "gaindB_desired": -12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 438.,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V4SA",
            "analog_filter": "U51A",
            "analog_output": "J6-1",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 1000,
            "fs": None,
            "max_sig_pm_mV": 10000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.25,
            "gaindB_desired": -12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 438.,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "HF12",
            "analog_filter": "HF12",
            "analog_output": None,
            "testpoint_plus": "U8-41",
            "testpoint_minus": "U8-42",
            "tm": 8000000.0,
            "fs": 8000000.0,
            "max_sig_pm_mV": 31.2488,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 9.615,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": 3000.,
            "lpf": 3500000.,
            "bits": 14,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "HF34",
            "analog_filter": "HF56",
            "analog_output": None,
            "testpoint_plus": "U4-41",
            "testpoint_minus": "U4-42",
            "tm": 8000000.0,
            "fs": 8000000.0,
            "max_sig_pm_mV": 15.6244,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 4.8075,
            "gain_desired": 80.00,
            "gaindB_desired": 38.1,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": 3000,
            "lpf": 3500000,
            "bits": 14,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "A",
            "analog_filter": None,
            "analog_output": None,
            "testpoint_plus": "U63-4",
            "testpoint_minus": "U63-5",
            "tm": None,
            "fs": None,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": 0.000,
            "gain_desired": None,
            "gaindB_desired": None,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": None,
            "bits": None,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "TEMP",
            "analog_filter": "E",
            "analog_output": None,
            "testpoint_plus": "U51-4",
            "testpoint_minus": "U51-5",
            "tm": 100,
            "fs": 100,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 1.0e0,
            "gaindB_desired": 0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 44.,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {   #Catch-all mag channel containing magX, magY, magZ
            "signal": "mag",
            "analog_filter": "J",
            "analog_output": "J14-1",
            "testpoint_plus": "U31-1",
            "testpoint_minus": "U31-7",
            "tm": 2000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-60uT",
            "gain_desired": 1.000,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875.,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "magX",
            "analog_filter": "J",
            "analog_output": "J14-1",
            "testpoint_plus": "U31-1",
            "testpoint_minus": "U31-7",
            "tm": 2000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-60uT",
            "gain_desired": 1.000,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875.,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "magY",
            "analog_filter": "K",
            "analog_output": "J14-2",
            "testpoint_plus": "U34-1",
            "testpoint_minus": "U34-7",
            "tm": 2000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-60uT",
            "gain_desired": 1.000,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875.,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "magZ",
            "analog_filter": "L",
            "analog_output": "J14-3",
            "testpoint_plus": "U38-1",
            "testpoint_minus": "U38-7",
            "tm": 2000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-60uT",
            "gain_desired": 1.000,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875.,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "LPA",
            "analog_filter": "F",
            "analog_output": "J14-4",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 2000,
            "fs": 2000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 1.0,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875.,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        #NEED TO VERIFY LP1D*********************
        {
            "signal": "LP1D",
            "analog_filter": "F",
            "analog_output": None,
            "testpoint_plus": "U47-4",
            "testpoint_minus": "U47-5",
            "tm": 32000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-25uA",
            "gain_desired": 1.0,
            "gaindB_desired": 0.0,
            "gain_measured": 105060.6,
            "gaindB_measured": 100.429,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 14000.,
            "bits": 18,
            "coeffa": 2.3796e-05,
            "coeffb": -4.2446e-10,
            "polarity": None
        },
        #LP2D - NOTE: This was NOT used as a Langmuir Probe, rather as the sensor's PCB temperature (Paulo email Jun 2, 2025)
        {
            "signal": "LP2D",
            "analog_filter": "F",
            "analog_output": None,
            "testpoint_plus": "U47-4",
            "testpoint_minus": "U47-5",
            "tm": 32000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-25uA",
            "gain_desired": 1.0,
            "gaindB_desired": 0.0,
            "gain_measured": 105060.6,
            "gaindB_measured": 100.429,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 14000.,
            "bits": 18,
            "coeffa": 2.3796e-05,
            "coeffb": -4.2446e-10,
            "polarity": None
        }
    ]



    # GIRAFF381 channel specification - All rows as Python dictionary
    # From file  GIRAFF381 _CORRECTED_ channel spec with conversion equations.pdf
    giraff_data381 = [
        {
            "signal": "V12D",
            "analog_filter": "F4-3",
            "analog_output": None,
            "testpoint_plus": "U72-4",
            "testpoint_minus": "U72-5",
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 1251,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 385.0,
            "gain_desired": 2.00,
            "gaindB_desired": 6.0,
            "gain_measured": 1.963,
            "gaindB_measured": 5.860,
            "measured_mVm": 392,
            "hpf": None,
            "lpf": 14000,
            "bits": 18,
            "coeffa": 1.2733E+00,
            "coeffb": 1.4792E-04,
            "polarity": "Pos"
        },
        {
            "signal": "V34D",
            "analog_filter": "F4-4",
            "analog_output": None,
            "testpoint_plus": "U67-4",
            "testpoint_minus": "U67-5",
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 1251,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 385.0,
            "gain_desired": 2.00,
            "gaindB_desired": 6.0,
            "gain_measured": 1.962,
            "gaindB_measured": 5.852,
            "measured_mVm": 392,
            "hpf": None,
            "lpf": 14000,
            "bits": 18,
            "coeffa": 1.2745E+00,
            "coeffb": 1.2000E-03,
            "polarity": "Pos"
        },
        {
            "signal": "Only ADC",
            "analog_filter": "F4-1",
            "analog_output": None,
            "testpoint_plus": "U81-4",
            "testpoint_minus": "U81-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 625,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 272.0,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 28000,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "Only ADC",
            "analog_filter": "F4-5",
            "analog_output": None,
            "testpoint_plus": "U62-4",
            "testpoint_minus": "U62-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 625,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 272.0,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 28000,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "Only ADC",
            "analog_filter": "F4-6",
            "analog_output": None,
            "testpoint_plus": "U58-4",
            "testpoint_minus": "U58-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 625,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 272.0,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 28000,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "VLF41DADC/VLF12A FiltF4-2",
            "analog_filter": None,
            "analog_output": None,
            "testpoint_plus": "U77-4",
            "testpoint_minus": "U77-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 625,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 272.0,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 28000,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "VLF12D",
            "analog_filter": "F8-3",
            "analog_output": None,
            "testpoint_plus": "U33-4",
            "testpoint_minus": "U33-5",
            "tm": 1000000,
            "fs": 1000000,
            "max_sig_pm_mV": 125,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 38.5,
            "gain_desired": 20.00,
            "gaindB_desired": 26.0,
            "gain_measured": 20.032,
            "gaindB_measured": 26.035,
            "measured_mVm": 38,
            "hpf": 50,
            "lpf": 437500,
            "bits": 18,
            "coeffa": 1.2480E-01,
            "coeffb": -2.9853E-05,
            "polarity": "Pos"
        },
        {
            "signal": "VLF34D",
            "analog_filter": "F8-4",
            "analog_output": None,
            "testpoint_plus": "U28-4",
            "testpoint_minus": "U28-5",
            "tm": 1000000,
            "fs": 1000000,
            "max_sig_pm_mV": 125,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 38.5,
            "gain_desired": 20.00,
            "gaindB_desired": 26.0,
            "gain_measured": 20.113,
            "gaindB_measured": 26.069,
            "measured_mVm": 38,
            "hpf": 50,
            "lpf": 437500,
            "bits": 18,
            "coeffa": 1.2430E-01,
            "coeffb": 5.3245E-05,
            "polarity": "Pos"
        },
        {
            "signal": "VLF13D",
            "analog_filter": "F8-1/F4-1ADC",
            "analog_output": None,
            "testpoint_plus": "U81-4",
            "testpoint_minus": "U81-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 62,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 27.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": 41.322,
            "gaindB_measured": 32.324,
            "measured_mVm": 26,
            "hpf": 50,
            "lpf": 28000,
            "bits": 18,
            "coeffa": 6.0500E-02,
            "coeffb": 6.0527E-06,
            "polarity": "Pos"
        },
        {
            "signal": "VLF32D",
            "analog_filter": "F8-5/F4-5ADC",
            "analog_output": None,
            "testpoint_plus": "U62-4",
            "testpoint_minus": "U62-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 62,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 27.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": 39.683,
            "gaindB_measured": 31.972,
            "measured_mVm": 27,
            "hpf": 50,
            "lpf": 28000,
            "bits": 18,
            "coeffa": 6.3000E-02,
            "coeffb": -1.2360E-05,
            "polarity": "Pos"
        },
        {
            "signal": "VLF24D",
            "analog_filter": "F8-6/F4-6ADC",
            "analog_output": None,
            "testpoint_plus": "U58-4",
            "testpoint_minus": "U58-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 62,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 27.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": 41.254,
            "gaindB_measured": 32.309,
            "measured_mVm": 26,
            "hpf": 50,
            "lpf": 28000,
            "bits": 18,
            "coeffa": 6.0600E-02,
            "coeffb": -2.2854E-04,
            "polarity": "Neg"
        },
        {
            "signal": "VLF41D",
            "analog_filter": "F8-2/F4-2ADC",
            "analog_output": None,
            "testpoint_plus": "U77-4",
            "testpoint_minus": "U77-5",
            "tm": 64000,
            "fs": 64000,
            "max_sig_pm_mV": 62,
            "boom_length": 2.2981,
            "max_sig_pm_mVm": 27.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": 40.064,
            "gaindB_measured": 32.055,
            "measured_mVm": 27,
            "hpf": 50,
            "lpf": 28000,
            "bits": 18,
            "coeffa": 6.2400E-02,
            "coeffb": 1.2897E-05,
            "polarity": "Neg"
        },
        {
            "signal": "V1SD",
            "analog_filter": "MUX5",
            "analog_output": None,
            "testpoint_plus": "U55-7",
            "testpoint_minus": None,
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 5000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.5,
            "gaindB_desired": -6.0,
            "gain_measured": 0.509,
            "gaindB_measured": -5.871,
            "measured_mVm": 4915,
            "hpf": None,
            "lpf": 14000,
            "bits": 18,
            "coeffa": -4.9145E+00,
            "coeffb": -2.3000E-03,
            "polarity": "Neg"
        },
        {
            "signal": "V2SD",
            "analog_filter": "MUX6",
            "analog_output": None,
            "testpoint_plus": "U54-7",
            "testpoint_minus": None,
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 5000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.5,
            "gaindB_desired": -6.0,
            "gain_measured": 0.509,
            "gaindB_measured": -5.870,
            "measured_mVm": 4914,
            "hpf": None,
            "lpf": 14000,
            "bits": 18,
            "coeffa": -4.9139E+00,
            "coeffb": -2.5000E-03,
            "polarity": "Neg"
        },
        {
            "signal": "V3SD",
            "analog_filter": "MUX7",
            "analog_output": None,
            "testpoint_plus": "U55-1",
            "testpoint_minus": None,
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 5000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.5,
            "gaindB_desired": -6.0,
            "gain_measured": 0.509,
            "gaindB_measured": -5.872,
            "measured_mVm": 4915,
            "hpf": None,
            "lpf": 14000,
            "bits": 18,
            "coeffa": -4.9153E+00,
            "coeffb": -2.8000E-03,
            "polarity": "Neg"
        },
        {
            "signal": "V4SD",
            "analog_filter": "MUX4",
            "analog_output": None,
            "testpoint_plus": "U54-1",
            "testpoint_minus": None,
            "tm": 32000,
            "fs": 64000,
            "max_sig_pm_mV": 5000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.5,
            "gaindB_desired": -6.0,
            "gain_measured": 0.508,
            "gaindB_measured": -5.879,
            "measured_mVm": 4919,
            "hpf": None,
            "lpf": 14000,
            "bits": 18,
            "coeffa": -4.9193E+00,
            "coeffb": -2.7000E-03,
            "polarity": "Neg"
        },
        {
            "signal": "V12A",
            "analog_filter": "F4-3",
            "analog_output": "J6-5",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 2000,
            "fs": None,
            "max_sig_pm_mV": 625,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 192.3,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V34A",
            "analog_filter": "F4-4",
            "analog_output": "J6-13",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 2000,
            "fs": None,
            "max_sig_pm_mV": 625,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 192.3,
            "gain_desired": 4.00,
            "gaindB_desired": 12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "VLF12A",
            "analog_filter": "F8-3",
            "analog_output": "J6-11",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 32000,
            "fs": None,
            "max_sig_pm_mV": 62,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 19.2,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": 50,
            "lpf": 14000,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V1SA",
            "analog_filter": "U51B",
            "analog_output": "J6-3",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 1000,
            "fs": None,
            "max_sig_pm_mV": 10000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.25,
            "gaindB_desired": -12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 438,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V2SA",
            "analog_filter": "U51D",
            "analog_output": "J6-2",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 1000,
            "fs": None,
            "max_sig_pm_mV": 10000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.25,
            "gaindB_desired": -12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 438,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V3SA",
            "analog_filter": "U51C",
            "analog_output": "J6-4",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 1000,
            "fs": None,
            "max_sig_pm_mV": 10000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.25,
            "gaindB_desired": -12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 438,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "V4SA",
            "analog_filter": "U51A",
            "analog_output": "J6-1",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 1000,
            "fs": None,
            "max_sig_pm_mV": 10000,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 0.25,
            "gaindB_desired": -12.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 438,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "HF12",
            "analog_filter": "HF12",
            "analog_output": None,
            "testpoint_plus": "U8-41",
            "testpoint_minus": "U8-42",
            "tm": 8000000.0,
            "fs": 8000000.0,
            "max_sig_pm_mV": 31.2488,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 9.615,
            "gain_desired": 40.00,
            "gaindB_desired": 32.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": 3000,
            "lpf": 3500000,
            "bits": 14,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "HF34",
            "analog_filter": "HF56",
            "analog_output": None,
            "testpoint_plus": "U4-41",
            "testpoint_minus": "U4-42",
            "tm": 8000000.0,
            "fs": 8000000.0,
            "max_sig_pm_mV": 15.6244,
            "boom_length": 3.25,
            "max_sig_pm_mVm": 4.8075,
            "gain_desired": 80.00,
            "gaindB_desired": 38.1,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": 3000,
            "lpf": 3500000,
            "bits": 14,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "A",
            "analog_filter": None,
            "analog_output": None,
            "testpoint_plus": "U63-4",
            "testpoint_minus": "U63-5",
            "tm": None,
            "fs": None,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": 0.000,
            "gain_desired": None,
            "gaindB_desired": None,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": None,
            "bits": None,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "TEMP",
            "analog_filter": "E",
            "analog_output": None,
            "testpoint_plus": "U51-4",
            "testpoint_minus": "U51-5",
            "tm": 100,
            "fs": 100,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 1.0e0,
            "gaindB_desired": 0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 44,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        { #catch-all mag channel containing magX, magY, magZ
            "signal": "mag",
            "analog_filter": "J",
            "analog_output": "J14-1",
            "testpoint_plus": "U31-1",
            "testpoint_minus": "U31-7",
            "tm": 2000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-60uT",
            "gain_desired": 1.000,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "magX",
            "analog_filter": "J",
            "analog_output": "J14-1",
            "testpoint_plus": "U31-1",
            "testpoint_minus": "U31-7",
            "tm": 2000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-60uT",
            "gain_desired": 1.000,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "magY",
            "analog_filter": "K",
            "analog_output": "J14-2",
            "testpoint_plus": "U34-1",
            "testpoint_minus": "U34-7",
            "tm": 2000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-60uT",
            "gain_desired": 1.000,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "magZ",
            "analog_filter": "L",
            "analog_output": "J14-3",
            "testpoint_plus": "U38-1",
            "testpoint_minus": "U38-7",
            "tm": 2000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-60uT",
            "gain_desired": 1.000,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875,
            "bits": 18,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        {
            "signal": "LPA",
            "analog_filter": "F",
            "analog_output": "J14-4",
            "testpoint_plus": None,
            "testpoint_minus": None,
            "tm": 2000,
            "fs": 2000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": None,
            "gain_desired": 1.0,
            "gaindB_desired": 0.0,
            "gain_measured": None,
            "gaindB_measured": None,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 875,
            "bits": 10,
            "coeffa": None,
            "coeffb": None,
            "polarity": None
        },
        #NEED TO VERIFY LP1D*********************
        {
            "signal": "LP1D",
            "analog_filter": "F",
            "analog_output": None,
            "testpoint_plus": "U47-4",
            "testpoint_minus": "U47-5",
            "tm": 32000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-25uA",
            "gain_desired": 1.0,
            "gaindB_desired": 0.0,
            "gain_measured": 104351.891,
            "gaindB_measured": 100.370,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 14000,
            "bits": 18,
            "coeffa": 2.3957e-05,
            "coeffb": -2.2300e-08,
            "polarity": None
        },
        #LP2D: NOTE: This was NOT used as a Langmuir Probe, rather as the sensor's PCB temperature (Paulo email Jun 2, 2025)
        {
            "signal": "LP2D",
            "analog_filter": "F",
            "analog_output": None,
            "testpoint_plus": "U47-4",
            "testpoint_minus": "U47-5",
            "tm": 32000,
            "fs": 32000,
            "max_sig_pm_mV": None,
            "boom_length": None,
            "max_sig_pm_mVm": "+-25uA",
            "gain_desired": 1.0,
            "gaindB_desired": 0.0,
            "gain_measured": 104351.891,
            "gaindB_measured": 100.370,
            "measured_mVm": None,
            "hpf": None,
            "lpf": 14000,
            "bits": 18,
            "coeffa": 2.3957e-05,
            "coeffb": -2.2300e-08,
            "polarity": None
        }
    ]

    return giraff_data380, giraff_data381



